namespace Maliev.InvoiceService.Data.Models;

/// <summary>
/// Primary entity representing a billing document issued to a customer.
/// Supports invoice creation from quotations, manual entry, splitting, and payment tracking.
/// </summary>
public class Invoice
{
    /// <summary>
    /// Primary key
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Unique invoice number (e.g., INV-2025-00001), assigned on finalization
    /// </summary>
    public string? InvoiceNumber { get; set; }

    /// <summary>
    /// Foreign key to parent invoice (for split invoices)
    /// </summary>
    public Guid? ParentInvoiceId { get; set; }

    /// <summary>
    /// External customer ID
    /// </summary>
    public Guid CustomerId { get; set; }

    /// <summary>
    /// Customer legal name
    /// </summary>
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>
    /// Customer tax identification number
    /// </summary>
    public string CustomerTaxId { get; set; } = string.Empty;

    /// <summary>
    /// Full billing address
    /// </summary>
    public string BillingAddress { get; set; } = string.Empty;

    /// <summary>
    /// Optional shipping address
    /// </summary>
    public string? ShippingAddress { get; set; }

    /// <summary>
    /// Reference to quotation system
    /// </summary>
    public string? QuotationReference { get; set; }

    /// <summary>
    /// Customer purchase order number
    /// </summary>
    public string? PoNumber { get; set; }

    /// <summary>
    /// Invoice status (Draft, Finalized, Cancelled, PartiallyPaid, FullyPaid)
    /// </summary>
    public string Status { get; set; } = "Draft";

    /// <summary>
    /// ISO 4217 currency code
    /// </summary>
    public string Currency { get; set; } = "THB";

    /// <summary>
    /// Exchange rate at creation time (if multi-currency)
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Source of exchange rate (CurrencyService, Manual, Fallback)
    /// </summary>
    public string? ExchangeRateSource { get; set; }

    /// <summary>
    /// Sum of all line subtotals before tax
    /// </summary>
    public decimal Subtotal { get; set; }

    /// <summary>
    /// Total VAT/tax amount
    /// </summary>
    public decimal TaxAmount { get; set; }

    /// <summary>
    /// Withholding tax amount
    /// </summary>
    public decimal WithholdingTaxAmount { get; set; }

    /// <summary>
    /// Final invoice total (subtotal + tax - withholding)
    /// </summary>
    public decimal GrandTotal { get; set; }

    /// <summary>
    /// Date invoice was issued
    /// </summary>
    public DateTime IssueDate { get; set; }

    /// <summary>
    /// Payment due date
    /// </summary>
    public DateTime DueDate { get; set; }

    /// <summary>
    /// Number of days for payment (e.g., 30, 60, 90)
    /// </summary>
    public int PaymentTermsDays { get; set; } = 30;

    /// <summary>
    /// Late payment fee percentage
    /// </summary>
    public decimal? LateFeePercentage { get; set; }

    /// <summary>
    /// Timestamp when invoice was finalized
    /// </summary>
    public DateTime? FinalizedAt { get; set; }

    /// <summary>
    /// User ID who finalized the invoice
    /// </summary>
    public string? FinalizedBy { get; set; }

    /// <summary>
    /// Timestamp when invoice was cancelled
    /// </summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>
    /// User ID who cancelled the invoice
    /// </summary>
    public string? CancelledBy { get; set; }

    /// <summary>
    /// Reason for cancellation
    /// </summary>
    public string? CancellationReason { get; set; }

    /// <summary>
    /// File reference (URL or ID) to PDF document generated by PDF Service.
    /// Registered via Upload Service callback after PDF generation.
    /// </summary>
    public string? PdfFileReference { get; set; }

    /// <summary>
    /// Soft delete flag
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Optimistic concurrency token (must be manually incremented for PostgreSQL)
    /// </summary>
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();

    /// <summary>
    /// Record creation timestamp
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Record last update timestamp
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    // Navigation properties
    public Invoice? ParentInvoice { get; set; }
    public ICollection<Invoice> ChildInvoices { get; set; } = new List<Invoice>();
    public ICollection<InvoiceLine> Lines { get; set; } = new List<InvoiceLine>();
    public ICollection<InvoicePaymentAllocation> InvoicePaymentAllocations { get; set; } = new List<InvoicePaymentAllocation>();
    public ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();
    public ICollection<FileReference> FileReferences { get; set; } = new List<FileReference>();
}
