// <auto-generated />
using System;
using Maliev.InvoiceService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.InvoiceService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("invoice_number_seq");

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("idx_audit_logs_actor_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_audit_logs_invoice_id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("idx_audit_logs_archived")
                        .HasFilter("is_archived = FALSE");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_logs_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.BillingNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("billing_address");

                    b.Property<string>("BillingNoteNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("billing_note_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerTaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_tax_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_billing_notes");

                    b.HasIndex("BillingNoteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_billing_notes_billing_note_number");

                    b.ToTable("billing_notes");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.BillingNoteInvoice", b =>
                {
                    b.Property<Guid>("BillingNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_note_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("IncludedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("included_amount");

                    b.HasKey("BillingNoteId", "InvoiceId")
                        .HasName("pk_billing_note_invoices");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_billing_note_invoices_invoice_id");

                    b.ToTable("billing_note_invoices");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.CreditTerm", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_credit_terms");

                    b.ToTable("credit_terms");

                    b.HasData(
                        new
                        {
                            Code = "COD",
                            Days = 0,
                            Description = "Payment due upon delivery",
                            IsActive = true,
                            Name = "Cash on Delivery"
                        },
                        new
                        {
                            Code = "NET7",
                            Days = 7,
                            Description = "Payment due within 7 days",
                            IsActive = true,
                            Name = "Net 7"
                        },
                        new
                        {
                            Code = "NET15",
                            Days = 15,
                            Description = "Payment due within 15 days",
                            IsActive = true,
                            Name = "Net 15"
                        },
                        new
                        {
                            Code = "NET30",
                            Days = 30,
                            Description = "Payment due within 30 days",
                            IsActive = true,
                            Name = "Net 30"
                        },
                        new
                        {
                            Code = "NET45",
                            Days = 45,
                            Description = "Payment due within 45 days",
                            IsActive = true,
                            Name = "Net 45"
                        },
                        new
                        {
                            Code = "NET60",
                            Days = 60,
                            Description = "Payment due within 60 days",
                            IsActive = true,
                            Name = "Net 60"
                        },
                        new
                        {
                            Code = "NET90",
                            Days = 90,
                            Description = "Payment due within 90 days",
                            IsActive = true,
                            Name = "Net 90"
                        },
                        new
                        {
                            Code = "2/10NET30",
                            Days = 30,
                            Description = "2% discount if paid within 10 days",
                            IsActive = true,
                            Name = "2% 10 Net 30"
                        },
                        new
                        {
                            Code = "EOM",
                            Days = 30,
                            Description = "Due end of invoice month",
                            IsActive = true,
                            Name = "End of Month"
                        },
                        new
                        {
                            Code = "EOM15",
                            Days = 45,
                            Description = "Due 15 days after EOM",
                            IsActive = true,
                            Name = "End of Month + 15"
                        },
                        new
                        {
                            Code = "EOM30",
                            Days = 60,
                            Description = "Due 30 days after EOM",
                            IsActive = true,
                            Name = "End of Month + 30"
                        },
                        new
                        {
                            Code = "MFI",
                            Days = 45,
                            Description = "Due end of month following invoice",
                            IsActive = true,
                            Name = "Month Following Invoice"
                        },
                        new
                        {
                            Code = "DEPOSIT50",
                            Days = 0,
                            Description = "50% upfront, balance on delivery",
                            IsActive = true,
                            Name = "50% Deposit"
                        },
                        new
                        {
                            Code = "DEPOSIT30",
                            Days = 0,
                            Description = "30% upfront, balance on delivery",
                            IsActive = true,
                            Name = "30% Deposit"
                        },
                        new
                        {
                            Code = "MILESTONE",
                            Days = 0,
                            Description = "Payment per milestone",
                            IsActive = true,
                            Name = "Milestone"
                        },
                        new
                        {
                            Code = "CIA",
                            Days = 0,
                            Description = "Full payment before work begins",
                            IsActive = true,
                            Name = "Cash in Advance"
                        },
                        new
                        {
                            Code = "CBD",
                            Days = 0,
                            Description = "Payment required before shipment",
                            IsActive = true,
                            Name = "Cash Before Delivery"
                        },
                        new
                        {
                            Code = "PREPAID",
                            Days = 0,
                            Description = "Full payment before invoice",
                            IsActive = true,
                            Name = "Prepaid"
                        });
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.FileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Checksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("file_url");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generated_by");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_file_references");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_file_references_invoice_id");

                    b.ToTable("file_references", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Key", "Operation")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_keys_expires_at");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("idx_idempotency_keys_resource_id");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_address");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreditTermCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credit_term_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("THB")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerTaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_tax_id");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ExchangeRateSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange_rate_source");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finalized_at");

                    b.Property<string>("FinalizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("finalized_by");

                    b.Property<decimal>("GrandTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grand_total");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<decimal?>("LateFeePercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("late_fee_percentage");

                    b.Property<Guid?>("ParentInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_invoice_id");

                    b.Property<int>("PaymentTermsDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("payment_terms_days");

                    b.Property<string>("PdfFileReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("pdf_file_reference");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("po_number");

                    b.Property<string>("QuotationReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quotation_reference");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("WithholdingTaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("withholding_tax_amount");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CreditTermCode")
                        .HasDatabaseName("ix_invoices_credit_term_code");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_invoices_customer_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("idx_invoices_due_date");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_invoices_invoice_number_unique");

                    b.HasIndex("IssueDate")
                        .IsDescending()
                        .HasDatabaseName("idx_invoices_issue_date");

                    b.HasIndex("ParentInvoiceId")
                        .HasDatabaseName("idx_invoices_parent_id")
                        .HasFilter("parent_invoice_id IS NOT NULL");

                    b.HasIndex("QuotationReference")
                        .HasDatabaseName("idx_invoices_quotation_reference")
                        .HasFilter("quotation_reference IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoices_status");

                    b.HasIndex("DueDate", "GrandTotal")
                        .HasDatabaseName("idx_invoices_pending_payment")
                        .HasFilter("status IN ('Finalized', 'PartiallyPaid') AND is_deleted = FALSE");

                    b.HasIndex("CustomerId", "Status", "IssueDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_invoices_customer_status_dates")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_percentage");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_code");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineSubtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_subtotal");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("VAT")
                        .HasColumnName("tax_category");

                    b.Property<decimal>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(7.00m)
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_invoice_lines");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_invoice_lines_invoice_id");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("idx_invoice_lines_item_code")
                        .HasFilter("item_code IS NOT NULL");

                    b.HasIndex("InvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_invoice_lines_invoice_line_unique");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.InvoicePaymentAllocation", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<string>("AllocatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("allocated_by");

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Confirmed")
                        .HasColumnName("allocation_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("InvoiceId", "PaymentId")
                        .HasName("pk_invoice_payment_allocations");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_invoice_payment_allocations_payment_id");

                    b.HasIndex("InvoiceId", "AllocationStatus")
                        .HasDatabaseName("idx_invoice_payment_allocations_invoice_status");

                    b.ToTable("invoice_payment_allocations", (string)null);
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payment_amount");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recorded_by");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_number");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("PaymentDate")
                        .IsDescending()
                        .HasDatabaseName("idx_payments_payment_date");

                    b.HasIndex("ReferenceNumber")
                        .HasDatabaseName("idx_payments_reference_number")
                        .HasFilter("reference_number IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_~");

                    b.ToTable("outbox_message");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "Invoice")
                        .WithMany("AuditLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.BillingNoteInvoice", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.BillingNote", "BillingNote")
                        .WithMany("BillingNoteInvoices")
                        .HasForeignKey("BillingNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_billing_note_invoices_billing_notes_billing_note_id");

                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_note_invoices_invoices_invoice_id");

                    b.Navigation("BillingNote");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.FileReference", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "Invoice")
                        .WithMany("FileReferences")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_references_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.CreditTerm", "CreditTerm")
                        .WithMany()
                        .HasForeignKey("CreditTermCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invoices_credit_terms_credit_term_code");

                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "ParentInvoice")
                        .WithMany("ChildInvoices")
                        .HasForeignKey("ParentInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoices_invoices_parent_invoice_id");

                    b.Navigation("CreditTerm");

                    b.Navigation("ParentInvoice");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.InvoicePaymentAllocation", b =>
                {
                    b.HasOne("Maliev.InvoiceService.Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoicePaymentAllocations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_payment_allocations_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message__outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_~");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.BillingNote", b =>
                {
                    b.Navigation("BillingNoteInvoices");
                });

            modelBuilder.Entity("Maliev.InvoiceService.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChildInvoices");

                    b.Navigation("FileReferences");

                    b.Navigation("InvoicePaymentAllocations");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
