name: CI - Develop validation

on:
  push:
    branches:
      - develop

permissions:
  contents: read

concurrency:
  group: invoice-develop-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    permissions:
      contents: read
    uses: ./.github/workflows/_validate.yml
