name: Validate - Main

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

env:
  ServiceDefaultsVersion: 1.0.82-alpha
  MessagingContractsVersion: 1.0.91-alpha

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
