name: CI - Main validation

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: invoice-main-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    permissions:
      contents: read
    uses: ./.github/workflows/_validate.yml
