name: Validate - Release Tag

on:
  push:
    tags: ["release/v*"]

permissions:
  contents: read

env:
  ServiceDefaultsVersion: 1.0.82-alpha
  MessagingContractsVersion: 1.0.91-alpha

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
