name: PR validation

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

concurrency:
  group: invoice-pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    permissions:
      contents: read
    uses: ./.github/workflows/_validate.yml
